export const UniqueActivities = {
    Foodpreparation: "Food preparation",
    Foodgrowthcollection: "Food growth & collection",
    Foodprocessing: "Food Processing",
    Materials: "Materials",
    Energy: "Energy",
    Infrastructure: "Infrastructure",
    Buildings: "Buildings",
    Artifacts: "Artifacts",
    Inhabitedenvironment: "Inhabited Environment",
    Sleepbedrest: "Sleep & Bed Rest",
    Wastemanagement: "Waste Management",
    Physicalchildcare: "Physical Child Care",
    Healthcare: "Health Care",
    Hygienegrooming: "Hygiene & Grooming",
    Schoolingresearch: "Schooling & Research",
    Religiouspractice: "Religious Practice",
    Humantransportation: "Human Transportation",
    Materialtransportation: "Material Transportation",
    Allocation: "Allocation",
    Social: "Social",
    Activerecreation: "Active Recreation",
    Meals: "Meals",
    Passive: "Passive",
    Interactive: "Interactive",
};