export const UniqueActivities = {
    FoodPrep: "Food preparation",
    FoodGrowth: "Food growth & collection",
    FoodProcessing: "Food Processing",
    Materials: "Materials",
    Energy: "Energy",
    Infrastructure: "Infrastructure",
    Buildings: "Buildings",
    Artifacts: "Artifacts",
    InhabitedEnv: "Inhabited Environment",
    SleepBedRest: "Sleep & Bed Rest",
    WasteManagement: "Waste Management",
    PhysChildCare: "Physical Child Care",
    Healthcare: "Health Care",
    Hygiene: "Hygiene & Grooming",
    SchoolingResearch: "Schooling & Research",
    Religion: "Religious Practice",
    HumanTransp: "Human Transportation",
    MaterialTransp: "Material Transportation",
    Allocation: "Allocation",
    Social: "Social",
    ActiveRecr: "Active Recreation",
    Meals: "Meals",
    Passive: "Passive",
    Interactive: "Interactive",
};